name: ${PROJECT_NAME}
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - APP_ENV=${APP_ENV}
      - PUID=${PUID} # user nginx
      - PGID=${PGID} # group www-data
    restart: unless-stopped
    volumes:
      - ./src/.:/var/www/html
    depends_on:
      - db
      # - redis
    ports:
      - "${APP_PORT:-443}:443"
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_grace_period: 1s
    networks:
      - laravel

  db:
    image: mysql:8.4.3
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - laravel

  # redis:
  #   image: redis:7.4-alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./redis:/data
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - laravel
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 3s
  #     retries: 3

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel
    stop_grace_period: 1s
    profiles:
      - dev

networks:
  laravel:
    driver: bridge
